week8/portfolio/internal/http/views/main_api.py
from flask import Blueprint, request, json, url_for, redirect, make_response, render_template, flash

from portfolio.enums.error.errors_enum import ErrorEnum
from portfolio.enums.success.success_enum import SuccessEnum
from portfolio.internal.biz.services.children import ChildrenService
from portfolio.internal.biz.services.employee import EmployeeService
from portfolio.internal.biz.services.events import EventsService
from portfolio.internal.biz.services.organisation import OrganisationService
from portfolio.internal.biz.services.request_to_organisation import RequestToOrganisationService
from portfolio.internal.http.wrappers.parents import get_parent_id_and_acc_id_with_confirmed_email
from portfolio.models.account_main import AccountMain
from portfolio.models.children import Children
from portfolio.models.events import Events
from portfolio.models.organisation import Organisation
from portfolio.models.parents import Parents
from portfolio.models.request_to_organisation import RequestToOrganisation

main = Blueprint('main', __name__, template_folder='templates/main', static_folder='static/main')


@main.route('/organisations', methods=['GET'])
@get_parent_id_and_acc_id_with_confirmed_email
def list_organisation(auth_account_main_id: int, parent_id: int):
    if request.method == 'GET':

        organisations, err = OrganisationService.get_all_organisations()

        if err:
            flash(err)
            return make_response(
                redirect(request.headers.get("Referer"))
            )
        response = make_response(render_template(
            'main/list_organisations.html',
            organisations=organisations
        ))
        return response


@main.route('/organisations/<int:organisation_id>', methods=['GET'])
@get_parent_id_and_acc_id_with_confirmed_email
def detail_organisation(auth_account_main_id: int, parent_id: int, organisation_id: int):
    if request.method == 'GET':
        organisation, err = OrganisationService.get_by_id(organisation_id)
        if err:
            flash(err)
            return make_response(
                redirect(request.headers.get("Referer"))
            )

        list_employee, err = EmployeeService.get_list_employee_by_org_id(organisation.id)
        if err:
            flash(err)
            return make_response(
                redirect(request.headers.get("Referer"))
            )

        list_active_events, err = EventsService.get_active_events_by_organisation_id(organisation.id)
        if err:
            flash(err)
            return make_response(
                redirect(request.headers.get("Referer"))
            )

        resp = make_response(
            render_template(
                'main/detail_organisation.html',
                organisation=organisation,
                list_employee=list_employee,
                count_employee=len(list_employee) if list_employee else 0,
                list_active_events=list_active_events,
                count_events=len(list_active_events) if list_active_events else 0,
            )
        )
        return resp


@main.route('/organisations/<int:organisation_id>/events/<int:events_id>', methods=['GET'])
@get_parent_id_and_acc_id_with_confirmed_email
def detail_event(auth_account_main_id: int, parent_id: int, organisation_id: int, events_id: int):
    if request.method == 'GET':
        events = Events(id=events_id)
        event, err = EventsService.get_by_events_id(events)
        if err:
            flash(err)
            return make_response(
                redirect(request.headers.get("Referer"))
            )

        children = Children(
            parents=Parents(
                id=parent_id,
            )
        )
        list_children, err = ChildrenService.get_children_by_parents_id(children)
        if err:
            flash(err)
            return make_response(
                redirect(request.headers.get("Referer"))
            )

        resp = make_response(
            render_template(
                'main/detail_event.html',
                event=event,
                list_children=list_children,
                organisation_id=organisation_id
            )
        )
        return resp


@main.route('/organisations/<int:organisation_id>/events/<int:events_id>/make_request', methods=['POST'])
@get_parent_id_and_acc_id_with_confirmed_email
def make_request(auth_account_main_id: int, organisation_id, events_id, parent_id: int):
    if request.method == 'POST':
        children_id = int(request.form.get('child_id'))
        if not children_id:
            flash(ErrorEnum.select_child_for_request)
            return make_response(
                redirect(request.headers.get("Referer"))
            )

        request_to_organisation = RequestToOrganisation(
            parents=Parents(id=parent_id),
            events=Events(id=events_id,
                          organisation=Organisation(id=organisation_id)),
            children=Children(id=children_id)
        )
        request_to_organisation, err = RequestToOrganisationService.make_request(request_to_organisation)
        if err:
            flash(err)
            resp = make_response(
                redirect(url_for('main.detail_event', events_id=events_id, organisation_id=organisation_id))
            )
            return resp

        flash(SuccessEnum.register_request)
        resp = make_response(
            redirect(url_for('main.detail_event', events_id=events_id, organisation_id=organisation_id))
        )
        return resp

week8/portfolio/templates/main/detail_event.html
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Кодировка веб-страницы -->
    <meta charset="utf-8">
    <!-- Настройка viewport -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>...</title>

    <!-- Bootstrap CSS (jsDelivr CDN) -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <!-- Bootstrap Bundle JS (jsDelivr CDN) -->
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
</head>
<body>
{% include 'navbar_parent.html' %}
{% with messages = get_flashed_messages() %}
  {% if messages %}
    <ul class=flashes>
    {% for message in messages %}
      <li>{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{% endwith %}
<div class="container-fluid">
  <div class="row">
    <div class="col-2 col-sm-2 col-md-2 col-xl-2 col-lg-2">
    </div>
    <div class="row col-8 col-sm-8 col-md-8 col-xl-8 col-lg-8 mt-5">
      <div class="info-event row col-7 col-sm-7 col-md-7 col-xl-7 col-lg-7 mt-5">
        <table class="table">
            <thead>
            <tr>
              <th scope="col">Тип события</th>
              <th scope="col">Название</th>
              <th scope="col">Дата события</th>
              <th scope="col">Количество часов</th>
              <th scope="col">Приобретаемый навык</th>
            </tr>
            </thead>
            <tbody>
            <tr>
              <td>{{ event.type }} </td>
              <td>{{ event.name }}</td>
              <td>{{ event.date_event }}</td>
              <td>{{ event.hours }}</td>
              <td>{{ event.skill }}</td>
            </tr>
            </tbody>
          </table>
      </div>
      <div class="link-event row col-5 col-sm-5 col-md-5 col-xl-5 col-lg-5 mt-5 d-flex flex-row-reverse">
          <img class="w-75" src="{{ url_for('static', filename='photos/organisation/icon_events.png') }}">
      </div>
    </div>
      <div class="col-2 col-sm-2 col-md-2 col-xl-2 col-lg-2">
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-2 col-sm-2 col-md-2 col-xl-2 col-lg-2">
    </div>
    <div class="row col-8 col-sm-8 col-md-8 col-xl-8 col-lg-8 mt-5 d-flex justify-content-center">
      <button style="width: 500px;" type="button" class="btn btn-info" data-bs-toggle="modal" data-bs-target="#exampleModal">
        Зарегистрировать ребенка на событие!
      </button>
    </div>
  </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
<div class="modal-dialog modal-dialog-centered" id="staticBackdrop">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form id="request_to_org" method="post" action="{{ url_for('main.make_request', events_id=event.id, organisation_id=organisation_id) }}">
          <div class="mb-3">
            <select id="child_id" name="child_id" form="request_to_org" class="form-select" aria-label="Default select example">
              <option selected>Выберите ребенка</option>
              {% for child in list_children %}
                <option value="{{ child.id }}">{{ child.name }} {{ child.surname }}</option>
              {% endfor %}
            </select>
          </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
          <button type="submit" class="btn btn-primary">Добавить</button>
        </div>
      </form>
    </div>
  </div>
</div>
</div>
</body>
</html>

week8/portfolio/templates/main/detail_organisation.html
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Кодировка веб-страницы -->
    <meta charset="utf-8">
    <!-- Настройка viewport -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>...</title>

    <!-- Bootstrap CSS (jsDelivr CDN) -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <!-- Bootstrap Bundle JS (jsDelivr CDN) -->
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
</head>
<body>
{% include 'navbar_parent.html' %}
<div class="container-fluid">
  <div class="row">
    <div class="col-2 col-sm-2 col-md-2 col-xl-2 col-lg-2">
    </div>
    <div class="row col-8 col-sm-8 col-md-8 col-xl-8 col-lg-8 mt-5">
      <div class="col-4 col-sm-4 col-md-4 col-xl-4 col-lg-4 mt-5">
          <h5>{{ organisation.name }}</h5>
          <h5>{{ organisation.login }}</h5>
          {% if organisation.description %}
          <p class="mt-5">
            {{ organisation.description }}
          </p>
          {% endif %}
        </div>
        <div class="row col-8 col-sm-8 col-md-8 col-xl-8 col-lg-8 mt-5 d-flex flex-row-reverse">
        {% if organisation.photo_link %}
          <img src="{{ organisation.photo_link }}" alt="">
        {% else %}
        <img class="w-50" src="{{ url_for('static', filename='photos/organisation/icon_org.png') }}" alt="">
        {% endif %}
      </div>

      </div>
    <div class="col-2 col-sm-2 col-md-2 col-xl-2 col-lg-2">
    </div>
  </div>
</div>
{% if list_teacher %}
<div class="container-fluid">
  <div class="row d-flex justify-content-center">
    <div class="col-6 col-sm-6 col-md-6 col-lg-6 col-xl-6 mt-5 ">
          <div class="header d-flex justify-content-center">
            Учителя организации
          </div>
          <div class="mt-3 header d-flex justify-content-center">
            <h5>В организации учителей:
              <span class="bg-info p-2" style="border-radius: 15px;">{{ count_teacher }}</span>
            </h5>
          </div>
          <table class="table">
            <thead>
            <tr>
              <th scope="col">Фамилия Имя преподавателя</th>
              <th scope="col">Специализация</th>
            </tr>
            </thead>
            <tbody>
            {% for teacher in list_teacher %}
            <tr>
              <td>{{ teacher.name }} {{ teacher.surname }}</td>
              <td>{{ teacher.specialty }}</td>
            </tr>
            {% endfor %}
            </tbody>
          </table>
    </div>
  </div>
</div>
{% else %}
<div class="container-fluid">
  <div class="row d-flex justify-content-center">
    <div class="col-6 col-sm-6 col-md-6 col-lg-6 col-xl-6 mt-5 ">
          <div class="header d-flex justify-content-center">
            В организации пока нет учителей
          </div>
    </div>
  </div>
</div>
{% endif %}

{% if list_active_events %}
<div class="container-fluid mb-5">
  <div class="row d-flex justify-content-center">
    <div class="col-6 col-sm-6 col-md-6 col-lg-6 col-xl-6 mt-5 ">
          <div class="mt-3 header d-flex justify-content-center">
            Мероприятия организации
          </div>
          <div class="header d-flex justify-content-center">
            <h5>В организации мероприятий:
              <span class="bg-info p-2" style="border-radius: 15px;">{{ count_events }}</span>
            </h5>
          </div>
          <table class="table">
            <thead>
            <tr>
              <th scope="col">Тип события</th>
              <th scope="col">Название</th>
              <th scope="col">Дата события</th>
              <th scope="col">Количество часов</th>
              <th scope="col">Приобретаемый навык</th>
              <th scope="col">Подробнее</th>
            </tr>
            </thead>
            <tbody>
            {% for event in list_active_events %}
            <tr>
              <td>{{ event.type }} </td>
              <td>{{ event.name }}</td>
              <td>{{ event.date_event }}</td>
              <td>{{ event.hours }}</td>
              <td>{{ event.skill }}</td>
              <td>
                <a class="btn btn-info" href="{{ url_for('main.detail_event', organisation_id=organisation.id, events_id=event.id) }}">
                  Подробнее
                </a>
              </td>
            </tr>
            {% endfor %}
            </tbody>
          </table>
    </div>
  </div>
</div>
{% else %}
<div class="container-fluid">
  <div class="row d-flex justify-content-center">
    <div class="col-6 col-sm-6 col-md-6 col-lg-6 col-xl-6 mt-5 ">
          <div class="header d-flex justify-content-center">
            В организации пока нет активных событий
          </div>
    </div>
  </div>
</div>
{% endif %}
</body>
</html>

week8/portfolio/templates/main/list_organisations.html
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Кодировка веб-страницы -->
    <meta charset="utf-8">
    <!-- Настройка viewport -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>...</title>

    <!-- Bootstrap CSS (jsDelivr CDN) -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <!-- Bootstrap Bundle JS (jsDelivr CDN) -->
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
</head>
<body>
{% include 'navbar_parent.html' %}
<div class="container-fluid">
  <div class="row">
    {% if organisations %}
    {% for organisation in organisations %}
    <div class="col-2 col-sm-2 col-md-2 col-xl-2 col-lg-2">
    </div>
    <div class="row col-8 col-sm-8 col-md-8 col-xl-8 col-lg-8 mt-5">
        <div class="col-4 col-sm-4 col-md-4 col-xl-4 col-lg-4 mt-5">
          <h5>{{ organisation.name }}</h5>
          <h5>{{ organisation.login }}</h5>
          {% if organisation.description %}
          <p class="mt-5">
            {{ organisation.description }}
          </p>
          {% endif %}
          <a class="mt-5 btn btn-info" href="{{ url_for('main.detail_organisation', organisation_id=organisation.id) }}">
            Подробнее
          </a>
      </div>
      <div class="row col-8 col-sm-8 col-md-8 col-xl-8 col-lg-8 mt-5 d-flex flex-row-reverse">
        {% if organisation.photo_link %}
          <img src="{{ organisation.photo_link }}" alt="">
        {% else %}
        <img class="w-50" src="{{ url_for('static', filename='photos/organisation/icon_org.png') }}" alt="">
        {% endif %}
      </div>
    </div>
    <div class="col-2 col-sm-2 col-md-2 col-xl-2 col-lg-2">

    </div>
    <div class="col-2 col-sm-2 col-md-2 col-xl-2 col-lg-2">

    </div>
    <hr>
    {% endfor %}
    {% else %}
    <div class="col-2 col-sm-2 col-md-2 col-xl-2 col-lg-2">

    </div>
    <div class="mt-5 col-6 col-sm-6 col-md-6 col-xl-6 col-lg-6">
      <h5 class="bg-light" style="border-radius: 10px; width: 350px;">Нет зарегистрированных компаний</h5>
    </div>
    {% endif %}
  </div>
</div>
</body>
</html>